version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for the root pom
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(java): "
    labels:
      - "dependencies"
    reviewers:
      - "npepinpe"
    target-branch: "master"
    ignore:
      - dependency-name: "io.zeebe:zeebe*" # Zeebe dependencies will be manually updated
