version: 2
updates:
  # Enable version updates for master
  - package-ecosystem: "maven"
    # Look for the root pom
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(master): "
    labels:
      - "dependencies"
    reviewers:
      - "npepinpe"
    target-branch: "master"
    open-pull-requests-limit: 10
  # Enable version updates for stable/2.0
  - package-ecosystem: "maven"
    # Look for the root pom
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(2.0): "
    labels:
      - "dependencies"
    reviewers:
      - "npepinpe"
    target-branch: "stable/2.0"
    open-pull-requests-limit: 10
