[[exporters]]
id = "kafka"
className = "io.zeebe.exporter.kafka.KafkaExporter"

  [exporters.args]
  default-topic = "zeebe"
  maxInFlightRecords = 1000
  servers = [ "kafka:9092" ]

  [exporters.args.producer]
  batchSize = "128K"
  batchLinger = "50ms"
  compressionType = "snappy"
  requestTimeout = "5s"

  [exporters.args.records]
  defaults = { type = [ "event" ], topic = "zeebe" }
  deployment = { topic = "zeebe-deployments" }
  incident = { topic = "zeebe-incidents" }
  jobBatch = { topic = "zeebe-incidents" }
  job = { topic = "zeebe-incidents" }
  message = { topic = "zeebe-incidents" }
  messageSubscription = { topic = "zeebe-incidents" }
  raft = { topic = "zeebe-incidents" }
  timer = { topic = "zeebe-incidents" }
  workflowInstance = { topic = "zeebe-incidents" }
  workflowInstanceSubscription = { topic = "zeebe-incidents" }
