[[exporters]]
id = "kafka"
className = "io.zeebe.exporter.kafka.KafkaExporter"

  [exporters.args]
  default-topic = "zeebe"
  maxInFlightRecords = 1000
  servers = [ "kafka:9092" ]

  [exporters.args.producer]
  batchSize = "128K"
  batchLinger = "50ms"
  compressionType = "snappy"
  requestTimeout = "5s"

  [exporters.args.records]
  defaults = { type = "all", topic = "zeebe" }
  deployment = { type = "all", topic = "zeebe-deployments" }
  incident = { type = "all", topic = "zeebe-incidents" }
  jobBatch = { type = "all", topic = "zeebe-incidents" }
  job = { type = "all", topic = "zeebe-incidents" }
  message = { type = "all", topic = "zeebe-incidents" }
  messageSubscription = { type = "all", topic = "zeebe-incidents" }
  raft = { type = "all", topic = "zeebe-incidents" }
  timer = { type = "all", topic = "zeebe-incidents" }
  workflowInstance = { type = "all", topic = "zeebe-incidents" }
  workflowInstanceSubscription = { type = "all", topic = "zeebe-incidents" }
